### ISSUE TITLE
css - 毛玻璃效果

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#10]
# css - 毛玻璃效果
参考文章：[如何使用 CSS 制作毛玻璃效果](https://chinese.freecodecamp.org/news/glassmorphism-design-effect-with-html-css/)

## 毛玻璃效果
对元素添加半透明的背景，以及阴影和边框。同时还要为背景加上模糊效果，使得背景之后的元素根据自身内容产生漂亮的“变形”效果。

## 方法
对元素设置一个半透明背景颜色，并使用 `backdrop-filter` 属性设置模糊效果。例如：
```css
.card {
	/* other styles */
	background: rgba(255, 255, 255, .7);  /* 设置半透明背景色 */
	-webkit-backdrop-filter: blur(10px);  
	backdrop-filter: blur(10px);  /* 设置背景模糊值 */
}
```
设置后，位于该元素下方遮盖的图片或样式，会变模糊，从而产生 “毛玻璃” 的效果。
