### ISSUE TITLE
css - 绘制三角形

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#12]
# css - 绘制三角形
参考文章：
* [纯 CSS 实现绘制三角形](https://www.cnblogs.com/chengxs/p/11406278.html)

## 原理
利用 border 的宽度及其透明度实现三角形。
1. width 和 height 都设置为 0
2. 确定三角形的底边，通过 border-方向：solid 2px red 设置
> 粗细，颜色等自定义，border 方向即为三角形底边方向，如 border-bottom

3. 设置三角形其他边：确保颜色为 transparent 透明，通过宽度来挤压底边 border 空间，形成尖角。

## 实现
![](https://www.mwcxs.top/static/upload/pics/2019/3/29UWmsYL8T8oUqP3A5RBQc7Wf4.png)
```css
#triangle-up {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-bottom: 100px solid red;
}
```
