### ISSUE TITLE
CSS - 隐藏元素滚动条

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#18]
# CSS - 隐藏元素滚动条

目的：隐藏滚动条，同时仍然可以在任何元素上滚动

如果需要在内容溢出时显示滚动条，只需要设置 `overflow：auto` 样式。
想要完全隐藏滚动条只需设置 `overflow：hidden` 即可，但是这样一来将导致元素内容不可滚动。

## Firefox浏览器
对于Firefox，我们可以将滚动条宽度设置为 none：
```css
scrollbar-width: none; /* Firefox */
```

## IE浏览器
对于IE，我们需要使用-ms-prefix属性定义滚动条样式：
```css
-ms-overflow-style: none; /* IE 10+ */
```

## Chrome和Safari浏览器
对于Chrome和Safari浏览器，我们必须使用CSS滚动条选择器，然后使用 `display：none` 隐藏它：
```css
::-webkit-scrollbar {
  display: none; /* Chrome Safari */
}
```
