### ISSUE TITLE
CSS - @font-face

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#19]
# 前言
CSS3 提供了 `@font-face` 规则，可以消除对用户电脑字体的依赖，使得开发者可以从项目外部或本地导入字体样式，并应用到项目中。
通常，字体样式文件的后缀为: `.ttf`, `.otf` 等等，字体样式可从网上查找下载。

# @font-face
## 示例
```css
@font-face
{
font-family: 'myFirstFont';
src: url('./assets/Sansation_Light.ttf'), /* 依照相对路径从本地读取字体样式文件 */
     url('https://xxx/Sansation_Light.eot'); /* 在线读取字体样式文件 */
}
```
`font-family` 属性：指定自定义字体样式调用的名称。以上述为例，加载外部的字体样式，并注册为 `myFirstFont` 供其他样式调用。
`src` 属性：指定字体样式文件的加载路径。
> 字体能从远程服务器或者用户本地安装的字体加载. 如果提供了 `local()` 函数，从用户本地查找指定的字体名称，并且找到了一个匹配项, 本地字体就会被使用. 否则, 字体就会使用 `url()` 函数下载的资源。`url()` 用于 css 内部文件加载，可传入相对路径/绝对路径/在线地址。
> `src` 属性可以同时配置加载多个字体样式文件

## 详细 API
* [CSS3 @font-face 规则](https://www.runoob.com/cssref/css3-pr-font-face-rule.html)
* [@font-face](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@font-face)

## 注意事项
注意 `@font-face` 定义的位置：
* CSS 样式表的最顶层
* `@规则`的条件规则组中
>  不能将 `@font-face` 定义到其他样式内部，例如 `.xxx`, `#xxx`, `body` 等。它同 `@key-frames` 一样都需要定义在 css 顶层。

`@font-face` 只是实现了在项目中引入字体样式并注册一个调用名称。我们还需要在 `font-family` 中使用注册的名称，才能在页面中展示下载的字体：
```css
@font-face {
  font-family: 'myFirstFont';
  src: url('./assets/Sansation_Light.ttf'), /* 依照相对路径从本地读取字体样式文件 */
       url('https://xxx/Sansation_Light.eot'); /* 在线读取字体样式文件 */
}

body {
  font-family: 'myFirstFont',
}
```
