### ISSUE TITLE
CSS 图片固定宽高比自适应缩放

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#25]
# CSS 图片宽高适配

## 前言

日常项目中，后端传图不规则，比例大小不一。前端又要去做适应，是一个让人非常头大的问题。因此，本文总结了一个不规则图片不变形的同时，可以铺满整个容器的解决方案。

### 一、背景图法

通过背景图的 `background-position` 属性，可以使图片居中显示。

```css
.box1 {
	background-image: url("https://hbimg.huabanimg.com/42d38784a9e5ad1cbce090966a7a87c274f5d27ba616-VMBaO0_fw658") 
  background-position: center center;
  background-repeat: no-repeat;
	background-size: auto 100%;
  /* background-size: 100% auto; */
  /* background-size: contain */
  /* background-size: cover */
}
```

> 同样 background-size 的 contain (完整显示)和 cover (填充)属性也能起到相同的效果。

### 二、object-fit

`object-fit` CSS 属性指定可替换元素的内容应该如何适应到其使用的高度和宽度确定的框，不支持IE。

可用属性：

- fill 不保持纵横比缩放图片，使图片完全适应
- contain 保持纵横比缩放图片，使图片的长边能完全显示出来
- cover 保持纵横比缩放图片，只保证图片的短边能完全显示出来
- none 保持图片宽高不变
- scale-down 当图片实际宽高小于所设置的图片宽高时，显示效果与none一致；否则，显示效果与contain一致
- inherit 继承
- initial 默认值
- unset 继承父元素，若父元素没有属性则显示默认值
