### ISSUE TITLE
CSS (Sass) :export - 导出变量至JS文件

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#27]
# :export
参考文章: [如何在Javascript和Sass之间共享变量](https://segmentfault.com/a/1190000020988598)

在环境之间共享变量是编程的圣杯。以下是在Javascript和Sass(CSS)之间共享变量的方法:

在Sass中定义实际的变量值，并将其导出到Javascript。CSS模块有一个名为的简洁实用程序 `:export`。该 `:export` 指令的工作原理基本上类似于ES6的export关键字。您的Sass代码将**导出一个对象**，其中包含要在Javascript中使用的变量名称及其关联的值。这些值都导出为字符串。

```css
// styles/animation.scss
$animation-length: 250;
$animation-length-ms: $animation-length + 0ms;

:export {
  animationMillis: $animation-length-ms;
}

.component-enter {
  ...

  transition: all $animation-length-ms ease-in;
}
```
现在，在Javascript中，我们只需要从样式表中导入样式，然后从导出的变量中解析使用即可:
```js
// js/animation.js
import styles from '../styles/animation.scss'
import CSSTransitionGroup from 'react-transition-group/CSSTransitionGroup'

const millis = parseInt(styles.animationMillis)

...

<CSSTransitionGroup
  transitionName="component"
  transitionEnterTimeout={millis}
  transitionLeaveTimeout={millis}
/>

...
```
