### ISSUE TITLE
CSS 字体平铺容器

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#28]
# CSS 字体平铺容器
参考文章：[css让字体平均铺满容器](https://blog.csdn.net/joyvonlee/article/details/108220554)

✅ **代码**
```html
<div class="label">账号</div>
```
```css
.label {
  width: 60px;
  height: 31px;
  line-height: 31px;
  padding-right: 10px;
  text-align: justify;
}
 
.label::after {
  display: inline-block;
  width: 100%;
  content: "";
}
```

🔆 **重点**
1. 明确容器的宽高
2. `text-align: justify`
3. `text-align` 生效条件需要两个元素，因此后面要添加上一个伪元素。
