### ISSUE TITLE
flex 布局 - 实现格网分布

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#29]
# flex 布局 - 实现格网分布

参考文章:
- [flex布局--每行固定数量+自适应布局](https://blog.csdn.net/weixin_41851906/article/details/106761873)
- [Flex 布局教程：语法篇](http://ruanyifeng.com/blog/2015/07/flex-grammar.html)

## 布局描述
页面每行预先分配 N 个固定的元素空槽，每个空槽所分配的空间是均匀的，元素按序均分到这些空槽中，若一行的空槽被全部分配，则换行进行下一行的分配。

## 代码
```css
//父盒子，设置为：
.templateItem {
  width: 100%;
  display: flex;
  align-content: flex-start;
  flex-flow: row wrap;
}

//子盒子，设置为：
 .template {
  flex: 0 0 25%;
}
```

✅ 父盒子设置：排列方式设置为 `flex-start`，从起始点开始放置子盒子，通过 `flex-flow` 设置换行。
> 如果不设置换行，那么子元素会缩小自声以达到放在一行的效果

✅ 子盒子设置：通过 `flex:0 0 25%`，设置子盒子的占位。通过均分宽度来指明子项目占的份数
> flex属性是 `flex-grow` , `flex-shrink` , `flex-basis` 的简写，默认值为 `0 , 1 , auto`
> 拆开说明：flex:0 0 25% 等于flex-grow=0（默认不放大）+flex-shrink=0（不缩小）+flex-basis=25%（ 项目占据主轴的空间）
