### ISSUE TITLE
CSS - "border-corner-shape"

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#6]
# CSS - "border-corner-shape"
参考文章：
[Understand CSS Border Corner Shape](https://www.hongkiat.com/blog/css3-border-shape/)

## 作用
`border-corner-shape` 在 CSS 样式中用于定义边角样式。
`border-radius` 可以实现圆角的创建，搭配上 `border-corner-shape` 则可实现斜角 bevel，铲形角 scoop 和矩形凹口角 notch 的创建。

## 语法
`border-corner-shape: (curve | scoop | bevel | notch)`
> 注意：`border-corner-shape` 仅声明边角形状，而形状的大小是使用 `border-radius` 属性指定的。因此，为了能够看到结果，在形成形状时应同时声明这两个属性。

## 实例
```css
.box {
  background-color: #3498DB;
  border-corner-shape: bevel;
  border-radius: 50% 50% 0% 50%;
  width: 200px;
  height: 200px;
}
```
![](https://assets.hongkiat.com/uploads/css3-border-shape/bevel.jpg)
