### ISSUE TITLE
sass - 变量导出

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#8]
# sass - 变量导出

参考文章：
[sass :export变量导出](https://my.oschina.net/shuaihong/blog/3127747)

将 `.scss` 中定义的样式变量导出，并在 `.js` 中使用。
```scss
/* config.scss */
$primary-color: #f40;

:export {
  primaryColor: $primary-color;
}
```
```js
/* app.js */
import style from 'config.scss';
// 会输出 #F40
console.log(style.primaryColor);
```
