### ISSUE TITLE
修改 Antd 某组件内部的默认样式

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/CSS-Note#9]
# 修改 Antd 某组件内部的默认样式

## 前言
在 Antd 中，组件通常向外提供了修改样式的接口，但是有时候我们需要更改组件内部嵌套部分的样式，这样通过样式接口是修改不了的。

## 需求
现有如下 css 结构 (ant-drawer-content-wrapper 同级还暴露了一个向外的样式接口)：
> 所谓样式接口就是：可以在元素中以自定义属性的方式，为元素添加样式的属性。该接口会在被设置后，以 class 形式添加到元素样式中
```js
ant-drawer-content-wrapper // 此处还暴露了一个样式接口
  ant-drawer-content
    ant-drawer-wrapper-body
```

需求是希望将背景色变透明，因此我们需要修改 `.ant-drawer-content` 的 background-color：
```css
.ant-drawer-content {
    position: relative;
    z-index: 1;
    overflow: auto;
    background-color: #fff;
    background-clip: padding-box;
    border: 0;
}
```
但问题是，我们无法在元素中利用自定义属性，style 或者 className 来覆盖该样式，因为这个样式存在于元素内部，我们添加的所有样式都只会合并到最外层元素的 class 内。

## 解决方法
1. F12 打开调试，选中 Elements 选项
2. 在 Elements 的元素树中选中相应的 Antd 组件布局，然后查看右端的 css 样式表，找到要覆盖的类名
3. 自定义一个 css 样式表，修改覆盖目标的样式：
```css
.ant-drawer-content {
  background-color: transparent !important;
}
```
> 不需要复制原有的样式，因为覆盖仅会合并相同的属性，不会替换原有的样式。
> `!important` 是必要的，这样确保我们自定义的 css 样式优先级高于 antd 的样式，从而实现覆盖效果。

4. 在 js 文件中导入 css 样式表即可
```js
import './xxx.css';
```
